// 389. Find the Difference
/*
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.
Return the letter that was added to t.

Example 1:
Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.

Example 2:
Input: s = "", t = "y"
Output: "y"

Constraints:
0 <= s.length <= 1000
*/

// CPP Solution
class Solution {
public:
    char findTheDifference(string s, string t) {
        int ans=0;
        for(int i=0;i<s.size();i++)
        {
            ans-=s[i];
            ans+=t[i];
        }
        ans+=t[s.size()];  
        return ans;
        
    }
};

// Python Solution

class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        s1 = Counter(s)
        t1 = Counter(t)
        for i in t1:
            if not s1[i] == t1[i]:
                return i
            